name = "prismatic"
author = "lizard_thief_fighter"
version = "0.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d578756219f44ccd0d429648506cf761e168f9d51cab1187835a419a7aa5a3f9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
