name = "prismatic"
author = "lizard_thief_fighter"
version = "0.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5011ef7247a4622ba16aa6bb23bfd8fbb397edfce03b520c86c9e68b179b8340"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
