name = "prismatic"
author = "lizard_thief_fighter"
version = "0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c63327c6f5b349363924c1e04afbb2775896b57dad540589d65413188f23db84"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
