name = "prismatic"
author = "lizard_thief_fighter"
version = "0.0g"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "264b72f8c6a0a165fd301471fcc99768933be5628960e61c5ed8c9067feaa87a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
