name = "prismatic"
author = "lizard_thief_fighter"
version = "0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bc6df437366d7c0679859e36e3db9a104800c7bad803e5f46148b0d60cefe24"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
