name = "prismatic"
author = "lizard_thief_fighter"
version = "0.0f"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b98375a85403016cc66415bf95041d2341adfcd43fc1ea7183328c8ceb73bbeb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
