name = "prismatic"
author = "lizard_thief_fighter"
version = "0.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6b8995cbf09683e2a3d75c941b0fc0aabdf232b8c6bd7fb2c020c00ee1bd3df"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
