# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				block_display = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.spectrum]
				eraser = true
				dragon_talon = true
				parametric_mining_device = true
				float_block = true
				splinterspawn = true
				egg_laying_wooly_pig = true
				light_mine = true
				item_projectile = true
				ink_projectile = true
				bedrock_fishing_bobber = true
				bident_mirror_image = true
				mining_projectile = true
				fireproof_item = true
				draconic_twinsword = true
				lizard = true
				lagoon_fishing_bobber = true
				light_spear = true
				light_shard = true
				shooting_star = true
				glass_arrow = true
				marrow = true
				seat = true
				monstrosity = true
				phantom_frame = true
				molten_fishing_bobber = true
				block_flooder_projectile = true
				kindling_cough = true
				living_marker = true
				bident = true
				glow_phantom_frame = true
				kindling = true
				preservation_turret = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.clutterbestiary]
				beaver = true
				booplet = true
				butterfly = true
				capybara = true
				chameleon = true
				coati = true
				crimson_newt = true
				dragonfly = true
				echofin = true
				ember_tortoise = true
				emperor_penguin = true
				jellyfish = true
				kiwi_bird = true
				koi = true
				manta_ray = true
				mossbloom = true
				potion_wasp = true
				red_panda = true
				river_turtle = true
				seahorse = true
				warped_newt = true
				koi_eggs = true
				potion_sac = true

			[light_sources.settings.entities.bountifulfares]
				flour = true

			[light_sources.settings.entities.oritech]
				portal_entity = true

			[light_sources.settings.entities.eternal_starlight]
				aethersent_arrow = true
				aethersent_golem = true
				aethersent_meteor = true
				air_sac_arrow = true
				amaramber_arrow = true
				ashen_snowball = true
				astral_golem = true
				aurora_deer = true
				ball_lightning = true
				boarwarf = true
				boat = true
				chest_boat = true
				chain_of_souls = true
				crest = true
				creteor = true
				crystal_cluster = true
				crystallized_moth = true
				energized_flame = true
				energy_boomerang = true
				energy_spark = true
				ent = true
				eye_of_seeking = true
				falling_block = true
				freeze = true
				frozen_bomb = true
				frozen_tube = true
				gatekeeper_fireball = true
				glacite_arrow = true
				gleech = true
				gleech_egg = true
				golem_laser_beam = true
				grimstone_golem = true
				lonestar_skeleton = true
				luminaris = true
				luminofish = true
				lunar_monstrosity = true
				lunar_monstrosity_breath = true
				lunar_spore = true
				lunar_thorn = true
				malarite_arrow = true
				malarite_spear = true
				nightfall_spider = true
				painting = true
				permafrost = true
				permafrost_cloud = true
				permafrost_spit = true
				poisonous_cloud = true
				pungency_fruit_spear = true
				ratlin = true
				rookfish = true
				seeker = true
				shadow_snail = true
				shattered_blade = true
				shimmer_lacewing = true
				shot_seeds = true
				sonar_bomb = true
				soulit_spectator = true
				starfire = true
				starfire_bird = true
				starlight_golem = true
				stranghoul = true
				tangled = true
				tangled_husk = true
				tangled_skull = true
				tear_bomb = true
				tear_bomb_minecart = true
				tentacle_spike = true
				the_gatekeeper = true
				thioquartz_arrow = true
				thioquartz_shard = true
				thirst_walker = true
				tiny_creteor = true
				twilight_gaze = true
				voracious_arrow = true
				wilted_petal = true
				yeti = true
				zombified_ratlin = true
				aetherstrike_rocket = true

			[light_sources.settings.entities.clutter]
				butterfly = true
				beaver = true
				capybara = true
				chameleon = true
				crimson_newt = true
				echofin = true
				ember_tortoise = true
				emperor_penguin = true
				jellyfish = true
				kiwi_bird = true
				manta_ray = true
				mossbloom = true
				seahorse = true
				seat = true
				warped_newt = true

			[light_sources.settings.entities.terraform]
				boat = true
				chest_boat = true

			[light_sources.settings.entities.xercapaint]
				canvas = true
				easel = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
